@startuml

entity "channels" as e01 {
+ channel_id [PK]
--
  channel_name
}

entity "time_slots" as e02 {
+ timeslot_id [PK]
--
  timeslot
}

entity "programs" as e03 {
+ program_id [PK]
--
  program_name
  program_detail
  genre
}

entity "episodes" as e04 {
+ episode_id [PK]
--
  program_id [FK]
  seasonn_number
  episode_number
  episode_title
  episode_detail
  duration
  release_date
}

entity "program_schedule" as e05 {
+ schedule_id [PK]
--
  channel_id [FK]
  timeslot_id [FK]
  program_id [FK]
  episode_id [FK]
}

entity "viewer_ship" as e06 {
+  viewership_id [PK]
--
  schedule_id [FK]
  viewcount
}

e03 ||-|{ e04
e03 ||-l-|{ e05
e05 ||-d-|{ e06
e01 ||-u-|{ e05
e02 ||-|{ e05
e04 ||-d-|{e05


@enduml
